### ISSUE TITLE
`image-slicing-tag-img` 无法正确解析某些图片的 URL

### ISSUE THREAD

**Issue by yangyingchao** [ginqi7/image-slicing#3]
例如网页： https://karthinks.com/software/fringe-matters-finding-the-right-difference/

**Comment by ginqi7** [comment]
十分感谢提出问题，并附加 PR。

由于有的 web 页面使用的是相对路径，而我使用 eww 时会通过 https://github.com/mozilla/readability 进行 URL 转换，之前没有发现这个问题。

推荐 eww 配合 readability 使用，效果更佳。

**Comment by yangyingchao** [comment]
试过，我比较喜欢直接用 eww 内置的 `(eww-readable)`，效果可能差点，但是更便于在隔离网络中使用。
